apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoer
  namespace: todoer
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: todoer
  template:
    metadata:
      labels:
        deployment: todoer
    spec:
      containers:
      - name: todoer
        image: vitorarins/todoer
        ports:
        - name: web
          containerPort: 8080
